"""Modify User Table Column Name

Revision ID: 9e8f9baa29e3
Revises: ca71bcb81946
Create Date: 2025-08-13 14:45:49.452919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e8f9baa29e3'
down_revision: Union[str, Sequence[str], None] = 'ca71bcb81946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('User', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('create_at', mysql.DATETIME(), nullable=False))
    op.drop_column('User', 'created_at')
    # ### end Alembic commands ###
